- README.md
Test release workflow with some non-code changes.
> feat: test release workflow with README changes

- README.md
> Alpha release test

- README.md
> Test release workflow

- src/editor/taxonomy-panel/index.js
> Alpha release Sep 08

- src/editor/taxonomy-panel/index.js
> Release Sep 08

- composer.json
- composer.lock
- includes/class-newspack-sponsors-core.php
- includes/newspack-sponsors-theme-helpers.php
> Alpha release Nov 24

- composer.json
- composer.lock
- includes/class-newspack-sponsors-core.php
- includes/newspack-sponsors-theme-helpers.php
> Release Nov 24

- includes/class-newspack-sponsors-core.php
> Alpha release May 04

- includes/class-newspack-sponsors-core.php
> Release May 04

- includes/newspack-sponsors-theme-helpers.php
> Alpha release May 13

- includes/newspack-sponsors-theme-helpers.php
> Release May 13

- includes/class-newspack-sponsors-core.php
- includes/newspack-sponsors-theme-helpers.php
> Alpha release Jun 15

- includes/class-newspack-sponsors-core.php
- includes/newspack-sponsors-theme-helpers.php
> Release Jun 15

- includes/class-newspack-sponsors-core.php
- includes/class-newspack-sponsors-editor.php
> Alpha release Sep 21

- includes/class-newspack-sponsors-core.php
- includes/class-newspack-sponsors-editor.php
> Release Sep 21

- includes/class-newspack-sponsors-core.php
- includes/class-newspack-sponsors-settings.php
> Alpha release Sep 24

- includes/class-newspack-sponsors-core.php
- includes/class-newspack-sponsors-settings.php
> Release Sep 24

- .github/dependabot.yml
Enables Dependabot for keeping NPM and Composer packages up-to-date. See [documentation](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates) for more details.
This config starts out with daily updates, which GitHub recommends when first enabling Dependabot as some packages may be very outdated at first. (For Sponsors, I just manually updated all NPM packages today, so this applies more for Composer than NPM.) After the incremental updates get us to a better place, we can drop back to a weekly or even monthly schedule.
Can't test this until it's merged to master. I guess this PR is more for discussion about whether we need/want this.
> feat: try enabling dependabot to keep dependencies up to date

- .github/dependabot.yml
As with our other dependabot-enabled repos, checks should be weekly instead of daily.
No functional changes.
> chore(deps): reduce frequency of dependabot checks

- includes/class-core.php
- includes/class-editor.php
- includes/class-settings.php
- includes/theme-helpers.php
- newspack-sponsors.php
Simplifies class names and filenames, since all are already namespaced.
This is a pure refactor, so there shouldn't be any editor or reader-facing changes. Smoke test creating/editing a native and underwriter sponsor, applying those to a post, and viewing the post on the front-end in a Homepage Posts block and as a singular post.
> refactor: simplify class names with namespaces

- .circleci/config.yml
- includes/class-core.php
- includes/class-editor.php
- includes/class-settings.php
- includes/theme-helpers.php
- newspack-sponsors.php
- package-lock.json
- package.json
- src/editor/index.js
- src/editor/sidebar/index.js
- src/editor/taxonomy-panel/index.js
> Alpha release Jul 14

- .prettierrc
- package-lock.json
- package.json
Similar to https://github.com/Automattic/newspack-theme/pull/1845 and https://github.com/Automattic/newspack-blocks/pull/1174, updates prettier, stylelint and Newspack scripts to the latest versions:
* newspack-scripts@4.0.0 was installed
* wp-prettier (aliased to prettier) were updated
* ran `npx sass-migrator module src/**/*.scss` to migrate styles (no changes made)
* ran `npm run lint:scss -- --fix` to fix any possible style errors (no changes made)
* ran `npm run lint:js -- --fix` to fix an possible JS errors (no changes made)
How to test the changes in this Pull Request:
1. Review the changes
2. Confirm all jobs pass in CI
3. Reinstall NPM fresh and run `npm run build`; confirm that no errors are thrown.
> chore: update newspack scripts, prettier

- .circleci/config.yml
- CHANGELOG.md
- includes/class-core.php
- includes/class-editor.php
- includes/class-settings.php
- includes/theme-helpers.php
- newspack-sponsors.php
- package-lock.json
- package.json
- src/editor/index.js
- src/editor/sidebar/index.js
- src/editor/taxonomy-panel/index.js
> Release Jul 25

- .prettierrc
- includes/class-core.php
- package-lock.json
- package.json
- src/editor/sidebar/index.js
> Alpha release Oct 06

- .prettierrc
- CHANGELOG.md
- includes/class-core.php
- newspack-sponsors.php
- package-lock.json
- package.json
- src/editor/sidebar/index.js
> Release Oct 19

- .circleci/config.yml
- composer.lock
- package-lock.json
- package.json
> Alpha release Jan 13

- .circleci/config.yml
- CHANGELOG.md
- composer.lock
- newspack-sponsors.php
- package-lock.json
- package.json
> Release Jan 13

- includes/theme-helpers.php
Fixes a small issue.
1. Activate Co-Authors Plus plugin, enable WP debugging (so that errors are logged)
2. On `master`, visit a guest author archive, note the error being logged about missing `taxonomy` property 
3. Switch to this branch, reload page, observe no error logged
> fix: ensure term has taxonomy

- includes/theme-helpers.php
> Alpha release Jan 26

- CHANGELOG.md
- includes/theme-helpers.php
- newspack-sponsors.php
- package-lock.json
- package.json
> Release Feb 15

- composer.json
- package-lock.json
- package.json
> Alpha release Mar 02

- CHANGELOG.md
- composer.json
- newspack-sponsors.php
- package-lock.json
- package.json
> Release Mar 13

- .circleci/config.yml
- CHANGELOG.md
- includes/class-core.php
- newspack-sponsors.php
- package-lock.json
- package.json
> Release Apr 10

- composer.lock
- includes/theme-helpers.php
- package-lock.json
- package.json
> Alpha release Sep 06

- CHANGELOG.md
- composer.lock
- includes/theme-helpers.php
- newspack-sponsors.php
- package-lock.json
- package.json
> Release Sep 13

- newspack-sponsors.php
- package-lock.json
- package.json
> Alpha release Oct 16

- CHANGELOG.md
- newspack-sponsors.php
- package-lock.json
- package.json
> Release Oct 31
